# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y:=

obj-y += vtss_core.o
obj-y += vtss_switch.o
obj-y += vtss_io.o
obj-y += vtss_sparx.o
obj-y += vtss_phy.o
obj-y += vtss_board.o

obj-$(CONFIG_VTSS_GROCX) += vtss_grocx.o
obj-$(CONFIG_VTSS_VERIPHY) += vtss_veriphy.o
obj-$(CONFIG_VTSS_CPU_FRAME) += vtss_cpu.o
obj-$(CONFIG_VTSS_ACL) += vtss_acl.o
