# Copyright (C) 2008 by Lv Zheng <lv.zheng@soliton.com.cn>
#
# Licensed under the GPL v2, see the file LICENSE in this tarball.

obj-y :=
obj-y += main.o
obj-y += init.o

hostprogs-y:=

always:= $(hostprogs-y)

